import { GetServerSideProps } from "next";
import nookies from "nookies";
import Head from "next/head";
import { useGlobalContext } from "@/contexts/GlobalContext";
import GlobalStyle from "@/styles/global";
import { lightTheme, darkTheme } from "@/styles/theme";
import { ThemeProvider } from "styled-components";
import HomePage from "@/components/pages/Home";
import { getUser, iUser } from "@/services/apiUser";

export interface iHomeProps {
  user: iUser;
}

export default function Home({ user }: iHomeProps) {
  const { theme } = useGlobalContext();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
        <GlobalStyle />
        <HomePage user={user} />
      </ThemeProvider>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = nookies.get(ctx);
  const token = cookies["@TokenKenzieM6E1"];

  if (!token) {
    return {
      redirect: { destination: "/login", permanent: false },
    };
  }

  try {
    const user = await getUser(token);

    return {
      props: { user: user },
    };
  } catch {
    return {
      redirect: { destination: "/login", permanent: false },
    };
  }
};
